sg_oauth.security.auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: SGOAuthBundle:OAuth:login }

sg_oauth.security.login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: SGOAuthBundle:OAuth:loginCheck }

sg_oauth.security.auth_logout:
    pattern:  /oauth/v2/logout
    defaults: { _controller: SGOAuthBundle:OAuth:login }