<?php

namespace RobatuDinero\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvestigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestigationRepository extends EntityRepository
{
}
