jms_serializer:
    metadata:
        directories:
            FOSUserBundle:
                namespace_prefix: 'FOS\UserBundle'
                path: '%kernel.root_dir%/Resources/FOSUserBundle/serializer'