nelmio_cors:
    paths:
        '^/api/':
            hosts: ['^api\.']
            allow_headers: ['Access-Control-Allow-Origin', 'X-Requested-With', 'Content-Type', 'Access-Control-Allow-Headers', 'x-wsse', 'authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_origin: ['*']

        '^/oauth/v2/':
            hosts: ['^api\.']
            allow_headers: ['Access-Control-Allow-Origin', 'X-Requested-With', 'Content-Type', 'Access-Control-Allow-Headers', 'x-wsse', 'authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_origin: ['*']
