#
# Backend
#
#backend:
#    resource:   "@RTDBackendBundle/Resources/config/routing.yml"
#    schemes:    [ https ]

#
# Frontend
#
#frontend:
#    prefix:     /
#    resource:   "@SGFrontendBundle/Resources/config/routing.yml"

#
# RTDApiBundle
#
#sg_api_bundle:
#    type:       rest
#    resource:   "@RTDApiBundle/Resources/config/routing.yml"
#    prefix:     /api
#    schemes:    [ https ]

#
# API Doc
#
nelmio_api_doc_bundle:
    resource:   "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:     /api/doc
    schemes:    [ https ]

#
# OAuth authentication
#
fos_oauth_server_token:
    resource:   "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    schemes:    [ https ]

fos_oauth_server_authorize:
    resource:   "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    schemes:    [ https ]

#
# OAuth login
#
#sg_oauth_bundle:
#    resource:   "@SGOAuthBundle/Resources/config/routing.yml"

#
# FOSUser
#
fos_user_security:
    resource:   "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource:   "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:     /profile

#fos_user_register:
#    host:       %admin_hostname%
#    resource:   "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix:     /register

fos_user_resetting:
    resource:   "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:     /resetting

fos_user_change_password:
    resource:   "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:     /profile